In [21]:
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x): #small derivation = less learning from past mistakes
    sx = sigmoid(x)
    return sx*(1-sx)

class Multi_layer_perceptron:
    def __init__(self, num_inputs, hidden_size1, hidden_size2, learning_rate=0.01):
        self.learning_rate = learning_rate

        # weights and biases for 2 hidden layers and one output layer
        self.weights1 = np.random.randn(num_inputs, hidden_size1)
        self.bias1 = np.zeros((1, hidden_size1))

        self.weights2 = np.random.randn(hidden_size1, hidden_size2)
        self.bias2 = np.zeros((1, hidden_size2))

        self.weights3 = np.random.randn(hidden_size2, 1)
        self.bias3 = np.zeros((1, 1))

    def forward(self, x):
        self.x=x
        # Weighted sum only, no activation functions
        self.z1 = np.dot(x, self.weights1) + self.bias1
        self.a1 = sigmoid(self.z1)
        
        self.z2 = np.dot(self.a1, self.weights2) + self.bias2
        self.a2 = sigmoid(self.z2)
        
        self.z3 = np.dot(self.a2, self.weights3) + self.bias3
        self.output = sigmoid(self.z3)
        
        return self.output

    def backward(self, y):
        output_err = self.output - y
        d_output = output_err*sigmoid_derivative(self.z3)
        
        error2 = np.dot(d_output, self.weights3.T)
        d_hidden2 = error2 * sigmoid_derivative(self.z2)

        error1 = np.dot(d_hidden2, self.weights2.T)
        d_hidden1 = error1 * sigmoid_derivative(self.z1)
        
        self.weights3 -= self.learning_rate * np.dot(self.a2.T, d_output)
        self.bias3 -= self.learning_rate * np.sum(d_output, axis=0, keepdims=True)

        self.weights2 -= self.learning_rate * np.dot(self.a1.T, d_hidden2)
        self.bias2 -= self.learning_rate * np.sum(d_hidden2, axis=0, keepdims=True)

        self.weights1 -= self.learning_rate * np.dot(self.x.T, d_hidden1)
        self.bias1 -= self.learning_rate * np.sum(d_hidden1, axis=0, keepdims=True)
        
    def train(self, x, y, epochs=1000):
        for e in range(epochs):
            self.forward(x)
            self.backward(y)

    def predict(self, x):
        output = self.forward(x)
        return (output > 0.5).astype(int)

# Example usage
training_input = np.array([
    [0, 0, 1],
    [1, 1, 0],
    [1, 0, 1],
    [0, 1, 1]
])

expected_output = np.array([
    [0],
    [1],
    [1],
    [0]
])

configs = [
    (3, 3, 3, 0.1),
    (3, 5, 4, 0.05),
    (3, 4, 2, 0.01)
]

for i, (num_inputs, h1, h2, lr) in enumerate(configs):
    print(f"\n--- Configuration {i+1}: Hidden1={h1}, Hidden2={h2}, LR={lr} ---")
    mlp = Multi_layer_perceptron(num_inputs=num_inputs, hidden_size1=h1, hidden_size2=h2, learning_rate=lr)
    mlp.train(training_input, expected_output, epochs=1000)

    input_data = np.array([
        [0, 0, 1],
        [1, 0, 0],
        [1, 0, 1],
        [1, 1, 1]
    ])

    preds = mlp.predict(input_data)
    print("Predictions:\n", preds)
    print("Weights1:\n", mlp.weights1)
    print("Weights2:\n", mlp.weights2)
    print("Weights3:\n", mlp.weights3)


--- Configuration 1: Hidden1=3, Hidden2=3, LR=0.1 ---
Predictions:
 [[0]
 [1]
 [1]
 [1]]
Weights1:
 [[-0.29161527  2.60666341 -2.83840131]
 [-0.50872079 -0.48209474 -0.08167273]
 [-0.14758807 -0.89700151  1.81357981]]
Weights2:
 [[-0.55601285  0.60597168 -0.35227089]
 [-2.37276675 -1.76266045  1.1124092 ]
 [ 2.08530142  2.08879465 -1.6120155 ]]
Weights3:
 [[-2.91273849]
 [-2.4232762 ]
 [ 2.145141  ]]

--- Configuration 2: Hidden1=5, Hidden2=4, LR=0.05 ---
Predictions:
 [[0]
 [1]
 [1]
 [1]]
Weights1:
 [[ 2.89628374  0.33056302 -1.56905567  1.96553577  1.21179769]
 [-0.13544082  0.45299883  0.75175869 -0.02977815  0.89522671]
 [-0.98573317  1.80086861  0.9447894   1.78604519 -0.81049165]]
Weights2:
 [[ 2.63160702 -1.01873114 -1.54305317  2.52951887]
 [-0.37387293  2.17594142  0.26739599  1.50266246]
 [-1.92981084  0.54283143  1.46776644  0.64012413]
 [-0.65905416 -0.73107207  0.16116622  0.50114594]
 [ 1.02448623 -1.75139211 -0.26476483  0.53601434]]
Weights3:
 [[ 3.52104565]
 [-1.99756