In [ ]:
import numpy as np

In [ ]:
class Perceptron:
    def __init__(self, W, learning_rate=0.01, n_iters=1000):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.activation_func = self._unit_step_func
        self.weights = W #None
        self.bias = None

    def fit(self, X, y):

        # init parameters
        self.bias = 0

        y_ = np.array([1 if i > 0 else 0 for i in y])

        linear_output = np.dot(np.transpose(self.weights) , X) + self.bias
        print(linear_output)
        y_predicted = self.activation_func(linear_output)

       # Perceptron update rule
        update = self.lr * (y - y_predicted)
        print(self.weights.shape)
        self.weights = self.weights + update * X
        self.bias += update

        print(self.weights)

    def _unit_step_func(self, x):
        return np.where(x >= 0, 1, 0)

In [ ]:
w=[1,-1,0,0.5]
wa=np.array(w)
wi=wa.reshape(4,1)
print(wi)
print(wi.shape)

[[ 1. ]
 [-1. ]
 [ 0. ]
 [ 0.5]]
(4, 1)


In [ ]:
#Testing
p = Perceptron(wi, learning_rate=0.01, n_iters=1)


In [ ]:
#data
x=[1,-2,0,-1]  #0,1.5,-0.5,-1,-1,1,0.5,-1]
xa=np.array(x)
xi=xa.reshape(4,1)
print(xi)
print(xi.shape)
o=[1]#1,1]
oa=np.array(o)
oi=oa.reshape(1,1)
print(oi)

[[ 1]
 [-2]
 [ 0]
 [-1]]
(4, 1)
[[1]]


In [ ]:
p.fit(xi,oi)

[[2.5]]
(4, 1)
[[ 1. ]
 [-1. ]
 [ 0. ]
 [ 0.5]]


In [ ]:
from sklearn.datasets import make_blobs
X, y = make_blobs(n_samples=10, centers=None, n_features=2,random_state=0)

In [ ]:
print(X)

[[ 1.12031365  5.75806083]
 [ 1.7373078   4.42546234]
 [ 2.36833522  0.04356792]
 [ 0.87305123  4.71438583]
 [-0.66246781  2.17571724]
 [ 0.74285061  1.46351659]
 [-4.07989383  3.57150086]
 [ 3.54934659  0.6925054 ]
 [ 2.49913075  1.23133799]
 [ 1.9263585   4.15243012]]


In [ ]:
print(y)

[0 0 1 0 2 2 2 1 1 0]
